//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.lo_infoSoap")]
    public interface lo_infoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLOInformationForOfficeID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetLOInformationForOfficeID(string userName, string password, string brand, string officeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLOInformationForOfficeID", ReplyAction="*")]
        System.Threading.Tasks.Task GetLOInformationForOfficeIDAsync(string userName, string password, string brand, string officeID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface lo_infoSoapChannel : test.ServiceReference1.lo_infoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class lo_infoSoapClient : System.ServiceModel.ClientBase<test.ServiceReference1.lo_infoSoap>, test.ServiceReference1.lo_infoSoap {
        
        public lo_infoSoapClient() {
        }
        
        public lo_infoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public lo_infoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lo_infoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lo_infoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetLOInformationForOfficeID(string userName, string password, string brand, string officeID) {
            base.Channel.GetLOInformationForOfficeID(userName, password, brand, officeID);
        }
        
        public System.Threading.Tasks.Task GetLOInformationForOfficeIDAsync(string userName, string password, string brand, string officeID) {
            return base.Channel.GetLOInformationForOfficeIDAsync(userName, password, brand, officeID);
        }
    }
}
